from snakemake.utils import min_version
from snakemake.remote import SFTP
from snakemake.remote import HTTP


min_version("6.10.0")


report: "report/report.rst"


configfile: "config/config.yaml"


envvars:
    "ZENODO_TOKEN",


include: "rules/common.smk"


https = HTTP.RemoteProvider()


module benchmark:
    snakefile:
        # TODO debugging, revert to tag
        #github("snakemake-workflows/dna-seq-benchmark", path="workflow/Snakefile", tag="v1.7.1")
        github("snakemake-workflows/dna-seq-benchmark", path="workflow/Snakefile", branch="update-datavzrd")
    config:
        config


use rule * from benchmark as benchmark_*

rule download_zenodo:
    input:
        get_zenodo_input,
    output:
        "resources/zenodo/{section}/{entry}/{path}",
    resources:
        disk_mb=5000,
        mem_mb=1000,
    shell:
        "mv {input} {output}"


rule download_https:
    input:
        https.remote("{url}"),
    output:
        "resources/https/{url}",
    resources:
        disk_mb=5000,
        mem_mb=1000,
    shell:
        "mv {input} {output}"
