variant-calls:
  # Minimal Beispiel to test.
  bonn-core-unit-agilent-200M:
    labels:
      site: bonn-core-unit
      reads: 200M
    subcategory: NA12878-agilent
    benchmark: giab-NA12878-agilent-200M
    rename-contigs: true
    zenodo:
      deposition: 6541919
      filename: 118711_200M.vcf.gz
  GHGA-sarek-dragmap-haplotypecaller-CHM-ERR1341796:
    labels:
      site: GHGA-Munich
      pipeline: nf-core/sarek v3.1 dragmap-haplotypecaller
      reads: 500M
    subcategory: CHM-eval
    zenodo:
      deposition: 7352532
      filename: ERR1341796_dragmap.haplotypecaller.filtered.vcf.gz
    benchmark: chm-eval
    rename-contigs: true
custom-benchmarks:
  giab-NA12878-agilent-200M:
    zenodo:
      deposition: 6513789
    genome: na12878
    fastqs:
      - resources/zenodo/custom-benchmarks/giab-NA12878-agilent-200M/A006850052_NA12878_200M_R1.fq.gz
      - resources/zenodo/custom-benchmarks/giab-NA12878-agilent-200M/A006850052_NA12878_200M_R2.fq.gz
    target-regions: resources/zenodo/custom-benchmarks/giab-NA12878-agilent-200M/Agilent_v7.bed
    grch37: false
    high-coverage: false
  giab-NA12878-agilent-75M:
    zenodo:
      deposition: 6513789
    genome: na12878
    fastqs:
      - resources/zenodo/custom-benchmarks/giab-NA12878-agilent-75M/A006850052_NA12878_75M_R1.fq.gz
      - resources/zenodo/custom-benchmarks/giab-NA12878-agilent-75M/A006850052_NA12878_75M_R2.fq.gz
    target-regions: resources/zenodo/custom-benchmarks/giab-NA12878-agilent-200M/Agilent_v7.bed # same bed as 200M
    grch37: false
    high-coverage: false
  giab-NA12878-twist:
    zenodo:
      deposition: 7075041
    genome: na12878
    fastqs:
      - resources/zenodo/custom-benchmarks/giab-NA12878-twist/NA12878_HG001_Twist_Bonn_1.fq.gz
      - resources/zenodo/custom-benchmarks/giab-NA12878-twist/NA12878_HG001_Twist_Bonn_2.fq.gz
    target-regions: resources/https/www.twistbioscience.com/sites/default/files/resources/2022-01/Twist_Comprehensive_Exome_Covered_Targets_hg38.bed
    grch37: false
    high-coverage: false
limit-regions:
  activate: false
reference-genome: grch38
